using IdentityService.Core.UserAggregate;
using IdentityService.UseCases.Abstractions.Authentication;

namespace IdentityService.UnitTests;

public class FakePasswordHasher : IPasswordHasher
{
    private const string Prefix = "HASHED_";
    
    /// <summary>
    /// Creates a deterministic test hash for the specified user password by prefixing its value with "HASHED_".
    /// </summary>
    /// <param name="password">The plain user password to hash.</param>
    /// <returns>A UserPasswordHash whose Value equals "HASHED_" followed by the original password value.</returns>
    public UserPasswordHash Hash(UserPassword password)
    {
        return UserPasswordHash.From($"{Prefix}{password.Value}");
    }

    /// <summary>
    /// Verifies that the provided password corresponds to the supplied password hash generated by this hasher.
    /// </summary>
    /// <param name="password">The plaintext password to verify.</param>
    /// <param name="passwordHash">The stored password hash to compare against.</param>
    /// <returns>`true` if <paramref name="passwordHash"/> equals "HASHED_" concatenated with <paramref name="password"/>.Value; `false` otherwise.</returns>
    public bool Verify(UserPassword password, UserPasswordHash passwordHash)
    {
        return passwordHash.Value == $"{Prefix}{password.Value}";
    }
}
