global using System.Collections.Generic;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
global using System.Runtime.CompilerServices;
global using Shouldly;
global using Mediator;
global using Microsoft.Extensions.Logging;
global using NSubstitute;
global using Xunit;
global using IdentityService.Core.UserAggregate;
// global using IdentityService.Core.UserAggregate.Events;
global using IdentityService.Core.UserAggregate.Specifications;
