# For more info on HTTP files go to https://aka.ms/vs/httpfile
@hostAddress = http://localhost:5268

// Add a new user
POST {{hostAddress}}/users/register
Content-Type: application/json

{
  "userName": "user1",
  "password": "test1234"
}

###